server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet

  web:
    resources:
      add-mappings: false

  security:
    user:
      name: user
      password: test1234

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}